# =====================================================
# 学生知识系统 - 统一配置文件
# =====================================================

server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: student-knowledge-system

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 注意：请根据实际情况选择数据库
    url: "jdbc:mysql://localhost:3306/student_knowledge_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8"
    username: root
    password: q18834366303  # 请根据实际情况修改
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis配置（如果需要）
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Spring MVC配置
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  # JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  # 环境配置
  profiles:
    active: dev

# MyBatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.csu.sms.model
  configuration:
    lazy-loading-enabled: false
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    root: INFO
    com.csu.sms.persistence: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.mybatis: DEBUG

# 阿里云通义千问API配置
alibaba:
  dashscope:
    api-key: sk-cc3666c2e5df4a31851c611908eb5275
    model: qwen-turbo

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # 例如: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucketName: students-sms # 你的 OSS Bucket 名称

app:
  upload:
    # 定义不同类型文件在 OSS 存储桶中的子文件夹
    avatar-folder: avatars/
    course-cover-folder: course-covers/
    video-folder: videos/
    # 你可以设置一个默认的头像URL，用于用户未上传头像时
    default-avatar-url: https://students-sms.oss-cn-chengdu.aliyuncs.com/avatars/defaultAvatar.png
    # 你可以设置一个默认的课程封面URL，用于课程未上传封面时
    default-course-cover-url: https://students-sms.oss-cn-chengdu.aliyuncs.com/course-covers/defaultCourseCover.jpg
    # 你可以设置一个默认的视频URL，用于课程未上传视频时
    default-video-url: https://your-education-platform-bucket.oss-cn-hangzhou.aliyuncs.com/videos/default_video.mp4
