server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: student_system
  config:
    import: optional:file:.env[.properties]
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: exam-booking-task-
  # AI评分配置
#  autoconfigure:
#    exclude:
#      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 注意：请根据实际情况选择数据库
#    url: "jdbc:mysql://localhost:3306/student_knowledge_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8"
    url: jdbc:mysql://127.0.0.1:3306/student_system
    username: root
    password: 123456  # 请根据实际情况修改
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis配置（如果需要）
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Spring MVC配置
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  # JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  # 环境配置
  profiles:
    active: dev
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API}
      base-url: https://api.deepseek.com/v1
      chat:
        options:
          model: deepseek-chat

# MyBatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.csu.sms.model
  type-handlers-package: com.csu.sms.handler
  configuration:
    lazy-loading-enabled: false
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.csu.sms.persistence: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.mybatis: DEBUG
    com.csu.sms.log: DEBUG

# 阿里云通义千问API配置
alibaba:
  dashscope:
    api-key: sk-cc3666c2e5df4a31851c611908eb5275
    model: qwen-turbo

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # 例如: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucketName: students-sms # 你的 OSS Bucket 名称

app:
  upload:
    # 定义不同类型文件在 OSS 存储桶中的子文件夹
    avatar-folder: avatars/
    course-cover-folder: course-covers/
    video-folder: videos/
    # 你可以设置一个默认的头像URL，用于用户未上传头像时
    default-avatar-url: https://students-sms.oss-cn-chengdu.aliyuncs.com/avatars/defaultAvatar.png
    # 你可以设置一个默认的课程封面URL，用于课程未上传封面时
    default-course-cover-url: https://students-sms.oss-cn-chengdu.aliyuncs.com/course-covers/defaultCourseCover.jpg
    # 你可以设置一个默认的视频URL，用于课程未上传视频时
    default-video-url: https://your-education-platform-bucket.oss-cn-hangzhou.aliyuncs.com/videos/default_video.mp4

# 考试预约相关配置
exam:
  booking:
    # 默认取消截止时间（小时）
    default-cancel-deadline: 24
    # 默认最大预约容量
    default-max-capacity: 50
    # 是否启用邮件通知
    email-notification-enabled: true
    # 是否启用短信通知
    sms-notification-enabled: false
    # 预约号前缀
    booking-number-prefix: "BK"
    # 通知保留天数
    notification-retention-days: 30

# 百度云人脸识别API配置
baidu:
  face:
    api-key: TVYsewoIomu9mS1Jpg4CKfW0   # 请替换为你在百度云控制台申请的人脸识别API Key
    secret-key: 9VS65XEDezLcpRHkENxeXILREKCC0HOp  # 请替换为你在百度云控制台申请的Secret Key
    group-id: student_system   # 建议与项目名一致，或自定义分组名

